### ISSUE TITLE
Awesome work

### ISSUE THREAD

**Issue by aleen42** [IonicaBizau/img-ssim#2]
Hah, actually, I can use a familiar technology to build a test tool for checking different rendering situations of sites crossing different platforms.

**Comment by IonicaBizau** [comment]
@aleen42 That's a neat idea. Don't forget to share it with me if you do it. 😁

**Comment by IonicaBizau** [comment]
What @notwaldorf did is so :cool:! :sparkles: I think we can close this issue now. :grin: 

https://meowni.ca/posts/2017-puppeteer-tests/

**Comment by notwaldorf** [comment]
🎉
